services:

  mongodb:
    image: mongo
    container_name: mongo_db_realWorld
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=novmah
      - MONGO_INITDB_ROOT_PASSWORD=novmah
  mongo-express:
    image: mongo-express
    container_name: mongo_express_realWorld
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=novmah
      - ME_CONFIG_MONGODB_ADMINPASSWORD=novmah
      - ME_CONFIG_MONGODB_SERVER=mongodb

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_realWorld
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_realWorld
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  mongo: {}